### ISSUE TITLE
Question: ACID compliance?

### ISSUE THREAD

**Issue by kim-toms** [Cimpress-MCP/git2consul#19]
I read the documentation but did not find if during the loading of the KV store from the git repo, it was possible for the KV store to be in an incorrect state vis-a-vis the state of the git repo.

The reason I ask is I'm considering using Consul Template, and wondering if it might be triggered multiple times during the update, if we update several keys.

**Comment by ryanbreen** [comment]
Consul Template would absolutely be triggered multiple times.  I don't think there's any way for me to solve this on the git2consul side: Consul has no atomic bulk update, so whatever updates I make will violate ACID.  I believe Consul Template supports a quiescence model, though, where you only render a template after N seconds of no updates.  That would likely be the guidance if you want to use Consul Template.

We use http://github.com/Cimpress-MCP/fsconsul instead, where each K/V represents a single file.  We'll never have a configuration file in an interim state since updates to single K/Vs are atomic.

**Comment by ryanbreen** [comment]
I'm going to close this since atomicity is not possible without Consul support.
