### ISSUE TITLE
Support ENV vars interpolation inside config json

### ISSUE THREAD

**Issue by dwelch2344** [Cimpress-MCP/git2consul#79]
We're looking at using this in a kubernetes cluster and it would be super nice to support interpolation of the config file, making it very easy to provide key details via `secrets`. 

Namely, to be able to create a public docker image with the following config bundled in: 
```
{
  "version": "1.0",
  "repos" : [{
    "name" : "$REPO_NAME",
    "url" : "$REPO_URL",
    "source_root": "$SOURCE_ROOT",
    "mountpoint": "$MOUNTPOINT",
    "branches" : ["$BRANCH"],
    "include_branch_name": $INCLUDE_BRANCH_NAME,
    "hooks": [{
      "type" : "polling",
      "interval" : "1"
    }]
  }]
}
```

Otherwise we have to create and host our own image, which isn't the end of the world but would be nice if we didn't need to.

**Comment by cleung2010** [comment]
This is a similar ask from #76. While we understand that principles such as 12factor states that config should live in the environment variable, we believe that for this type of configuration things should live in a file since the number of variables correlates with, and increases by, the number of repositories needed to configure. 

For instance with the proposed template, `$BRANCH` (and basically all the other env variable stated) would only work if you have one tracking repository. As more repository is added, the number of variables that is needed to track config for each repository also increases, which would make configuration non-trivial.

We like the model that the folks at [eBay/fabio](https://github.com/eBay/fabio) is using, which is to provide one flag (excluding `-v` for printing out the version) for passing in a config file and attempt to use sane defaults from the get-go. We will probably go down a similar route in future versions of git2consul.

As far as a workaround for deploying git2consul in a container, you can either mount the config file, or wrap git2consul in an entrypoint and create your config file via env vars that way.

**Comment by dwelch2344** [comment]
Yeah, I guess that's understandable. The wrap and mount is probably the way we'll end up going, as it fits our workflow pretty well. Thanks!
